name: docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v7
        with:
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
      - uses: actions/checkout@v4
      - uses: rlespinasse/github-slug-action@v4
      - uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "cropbox/cropbox-binder"
          ADDITIONAL_TAG: ${{ env.GITHUB_REF_SLUG }}
          MYBINDERORG_TAG: ${{ env.GITHUB_REF_SLUG }}
